# Generated by Django 3.1.14 on 2023-11-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231103_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.EmailField(max_length=254),
        ),
    ]
